language: php

php:
   # 7.2
   - 7.3
   - 7.4
   #- hhvm
   #- nightly



matrix:
    allow_failures:
        #- php: 7.2
        - php: 7.3
        #- php: nightly
        #- php: hhvm



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    # Prepare for automated tests
    - make install



script:
    # Run tests
    - make check test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/9758ddde9a8352ac88be

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
